### ISSUE TITLE
无法远程登录

### ISSUE THREAD

**Issue by Mapaler** [icelemon1314/mapleLemon#18]
我在淘宝上买的一个027单机端，后来想分离服务器客户端游玩发现无法远程登录。
看到文件里有个LICENSE，抱着死马当活马医的心态一搜，还居然真在GitHub上搜到了，我都不知道用什么表情了。

服务端配置
![服务端配置](http://ww2.sinaimg.cn/large/6c84b2d6ly1ff7gzjmc56j21kw0zke0x.jpg)
客户端配置
![客户端配置](http://ww1.sinaimg.cn/large/6c84b2d6ly1ff7h01vamnj20d709kt9v.jpg)

分别运行于同一台局域网的两台电脑上
客户端可以正常登陆、创建人物
![两台机器](http://ww1.sinaimg.cn/large/6c84b2d6ly1ff7h0oj4dmj20uk0h7juw.jpg)
但是无法进入游戏，点击“选择人物”后，就死掉了
![无法进入](http://ww3.sinaimg.cn/large/6c84b2d6ly1ff7h1d36i9j20uk0h7jva.jpg)

**Comment by icelemon1314** [comment]
027从来没有在网上售卖过。请找卖家退款。

现在的这个代码是没有办法做联机的，很多地方都没有修复，只能单机。

**Comment by Mapaler** [comment]
我是觉得这个可以跑在Linux上，就可以用VPS一直开着了，家里单位都可以玩。

**Comment by icelemon1314** [comment]
这样的话，你需要修改下客户端exe，在exe中搜索127.0.0.1，把他修改为你的vps的公网ip或者域名就行了。服务端也需要响应的修改。

**Comment by Mapaler** [comment]
看图上，服务端我改了，客户端没有修改exe，是直接用的参数启动，都可以进入到选择人物建立人物，但是后面不能继续进入游戏。
你的意思是后面需要能进入游戏的话，还得改exe的默认连接ip?也就是登录ip可以被参数修改但游玩时的ip不能被修改吗？

**Comment by icelemon1314** [comment]
服务端要改代码，重新编译的。
客户端用bat应该是没用的，最好直接改exe
